[controller]
host = "http://localhost:8000"
SecrectKey = "0xffffffff"
AccessKey = "ox00000000"
[self]
judgeCapability = 1000
name = "TestJudger"
version = "0.0.1"
[hc]
path = "/usr/local/bin/hc"
[nsjail]
path = "/usr/bin/nsjail"
configFile = "./jailConfig.cfg"
[language]
c = "/usr/bin/gcc"
cpp = "/usr/bin/g++"
python = "/usr/bin/python3"
java = "/usr/bin/java"
javac = "/usr/bin/javac"
[judger]
timeRatioTolerance = 5
cmp = '/usr/bin/ojcmp'
uid = 1000
gid = 1000
[[judger.testcases]]
src = "./selfTest/src.cpp"
language = "cpp"
timeExpected = 1000
[[judger.testcases]]
src = "./selfTest/Main.java"
language = "java"
timeExpected = 1000
[[judger.testcases]]
src = "./selfTest/src.py"
language = "py3"
timeExpected = 2000
